# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mymodule', [dirname(__file__)])
        except ImportError:
            import _mymodule
            return _mymodule
        if fp is not None:
            try:
                _mod = imp.load_module('_mymodule', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _mymodule = swig_import_helper()
    del swig_import_helper
else:
    import _mymodule
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Rectangle(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Rectangle, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Rectangle, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x0"] = _mymodule.Rectangle_x0_set
    __swig_getmethods__["x0"] = _mymodule.Rectangle_x0_get
    if _newclass:x0 = _swig_property(_mymodule.Rectangle_x0_get, _mymodule.Rectangle_x0_set)
    __swig_setmethods__["y0"] = _mymodule.Rectangle_y0_set
    __swig_getmethods__["y0"] = _mymodule.Rectangle_y0_get
    if _newclass:y0 = _swig_property(_mymodule.Rectangle_y0_get, _mymodule.Rectangle_y0_set)
    __swig_setmethods__["x1"] = _mymodule.Rectangle_x1_set
    __swig_getmethods__["x1"] = _mymodule.Rectangle_x1_get
    if _newclass:x1 = _swig_property(_mymodule.Rectangle_x1_get, _mymodule.Rectangle_x1_set)
    __swig_setmethods__["y1"] = _mymodule.Rectangle_y1_set
    __swig_getmethods__["y1"] = _mymodule.Rectangle_y1_get
    if _newclass:y1 = _swig_property(_mymodule.Rectangle_y1_get, _mymodule.Rectangle_y1_set)
    def __init__(self, *args): 
        this = _mymodule.new_Rectangle(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mymodule.delete_Rectangle
    __del__ = lambda self : None;
    def getLength(self): return _mymodule.Rectangle_getLength(self)
    def getHeight(self): return _mymodule.Rectangle_getHeight(self)
    def getArea(self): return _mymodule.Rectangle_getArea(self)
    def move(self, *args): return _mymodule.Rectangle_move(self, *args)
Rectangle_swigregister = _mymodule.Rectangle_swigregister
Rectangle_swigregister(Rectangle)

# This file is compatible with both classic and new-style classes.


